//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceReporting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbsenceReporting()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public short AbsenceReason { get; set; }
        public string ReasonDetails { get; set; }
        public Nullable<System.Guid> Document_ID { get; set; }
    
        public virtual UploadedDocument UploadedDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
