//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceReporting
    {
        public string UserId { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public Nullable<short> AbsenceReason { get; set; }
        public string ReasonDetails { get; set; }
        public byte[] ScannedDocument { get; set; }
    
        public virtual User User { get; set; }
    }
}
