//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public System.Guid Action_ID { get; set; }
        public string ActionName { get; set; }
        public string PerformedBy { get; set; }
        public Nullable<System.DateTime> PerformedDate { get; set; }
        public string Note { get; set; }
        public string Station { get; set; }
    
        public virtual Membership_Users Membership_Users { get; set; }
    }
}
