//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Queues = new HashSet<Queue>();
        }
    
        public System.Guid ID { get; set; }
        public string Timeslot_ID { get; set; }
        public Nullable<System.Guid> AbsenceReporting_ID { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public short ChangedCount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReportTime { get; set; }
    
        public virtual AbsenceReporting AbsenceReporting { get; set; }
        public virtual Membership_Users Membership_Users { get; set; }
        public virtual Timeslot Timeslot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queues { get; set; }
    }
}
