//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_USER_ACT_LOG
    {
        public long USER_ACT_LOG_ID { get; set; }
        public string UserId { get; set; }
        public string USER_ACT_LOG { get; set; }
        public string USER_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
    
        public virtual User_Profiles User_Profiles { get; set; }
    }
}
