//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugResult
    {
        public string DrugResultsID { get; set; }
        public string NRIC { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string markingnumber { get; set; }
        public Nullable<bool> AMPH { get; set; }
        public Nullable<bool> BENZ { get; set; }
        public Nullable<bool> OPI { get; set; }
        public Nullable<bool> THC { get; set; }
        public Nullable<bool> COCA { get; set; }
        public Nullable<bool> BARB { get; set; }
        public Nullable<bool> LSD { get; set; }
        public Nullable<bool> METH { get; set; }
        public Nullable<bool> MTQL { get; set; }
        public Nullable<bool> PCP { get; set; }
        public Nullable<bool> KET { get; set; }
        public Nullable<bool> BUPRE { get; set; }
        public Nullable<bool> CAT { get; set; }
        public Nullable<bool> PPZ { get; set; }
        public Nullable<bool> NPS { get; set; }
        public Nullable<bool> IsSealed { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> SealedOrDiscardedDate { get; set; }
        public string SealedOrDiscardedBy { get; set; }
    }
}
