//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public System.Guid Label_ID { get; set; }
        public string Label_Type { get; set; }
        public string CompanyName { get; set; }
        public string MarkingNo { get; set; }
        public string DrugType { get; set; }
        public string UserId { get; set; }
        public string NRIC { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] QRCode { get; set; }
        public string LastStation { get; set; }
        public int PrintCount { get; set; }
        public string ReprintReason { get; set; }
        public string PrintStatus { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> Queue_ID { get; set; }
    
        public virtual Membership_Users Membership_Users { get; set; }
    }
}
