//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership_UserDevices
    {
        public int Device_ID { get; set; }
        public string UserId { get; set; }
        public string User_Device_ID { get; set; }
        public string Terminal { get; set; }
        public bool Active { get; set; }
        public string Access_token { get; set; }
    
        public virtual Membership_Users Membership_Users { get; set; }
    }
}
