//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string NotificationID { get; set; }
        public System.DateTime Datetime { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsFromSupervisee { get; set; }
        public string Source { get; set; }
        public byte[] RecID { get; set; }
        public string Type { get; set; }
        public string notification_code { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual Membership_Users Membership_Users { get; set; }
        public virtual Membership_Users Membership_Users1 { get; set; }
    }
}
