//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueNumber
    {
        public System.Guid ID { get; set; }
        public System.Guid AppointmentID { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual User User { get; set; }
    }
}
