//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueDetail
    {
        public System.Guid Queue_ID { get; set; }
        public string Station { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
    
        public virtual Queue Queue { get; set; }
    }
}
