//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int RecID { get; set; }
        public Nullable<int> MsgID { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Email { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
    
        public virtual Membership_Users Membership_Users { get; set; }
        public virtual Message Message { get; set; }
    }
}
