//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SentMessage()
        {
            this.MsgRecipients = new HashSet<MsgRecipient>();
        }
    
        public int MsgID { get; set; }
        public string Subject { get; set; }
        public string MsgContent { get; set; }
        public Nullable<int> DelileryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Email { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsgRecipient> MsgRecipients { get; set; }
        public virtual User_Profiles User_Profiles { get; set; }
    }
}
