//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Year { get; set; }
        public string CompanyName { get; set; }
        public string VenueName { get; set; }
        public Nullable<int> MaxCardNumber { get; set; }
        public Nullable<int> MaxMarkingNo { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
    }
}
