//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Nullable<System.TimeSpan> Mon_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Mon_Close_Time { get; set; }
        public Nullable<int> Mon_Interval { get; set; }
        public Nullable<System.TimeSpan> Tue_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Tue_Close_Time { get; set; }
        public Nullable<int> Tue_Interval { get; set; }
        public Nullable<System.TimeSpan> Wed_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Wed_Close_Time { get; set; }
        public Nullable<int> Wed_Interval { get; set; }
        public Nullable<System.TimeSpan> Thu_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Thu_Close_Time { get; set; }
        public Nullable<int> Thu_Interval { get; set; }
        public Nullable<System.TimeSpan> Fri_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Fri_Close_Time { get; set; }
        public Nullable<int> Fri_Interval { get; set; }
        public Nullable<System.TimeSpan> Sat_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Sat_Close_Time { get; set; }
        public Nullable<int> Sat_Interval { get; set; }
        public Nullable<System.TimeSpan> Sun_Open_Time { get; set; }
        public Nullable<System.TimeSpan> Sun_Close_Time { get; set; }
        public Nullable<int> Sun_Interval { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public int MaxSuperviseePerTimeslot { get; set; }
        public int ReservedForSpare { get; set; }
    }
}
