//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid ID { get; set; }
        public string NRIC { get; set; }
        public string TransactionCode { get; set; }
        public string Source { get; set; }
        public System.DateTime datetime { get; set; }
        public string Content { get; set; }
    }
}
