//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.DAL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedDocumentDetail
    {
        public System.Guid DocumentDetail_ID { get; set; }
        public System.Guid Document_ID { get; set; }
        public byte[] DocumentContent { get; set; }
    
        public virtual UploadedDocument UploadedDocument { get; set; }
    }
}
