//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uhpSim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UHPSimulatorIIEntities : DbContext
    {
        public UHPSimulatorIIEntities()
            : base("name=UHPSimulatorIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DrugResult> DrugResults { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    
        public virtual ObjectResult<USP_DrugResult_SELECT_MarkingNumber_Result> USP_DrugResult_SELECT_MarkingNumber(string markingnumber)
        {
            var markingnumberParameter = markingnumber != null ?
                new ObjectParameter("markingnumber", markingnumber) :
                new ObjectParameter("markingnumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DrugResult_SELECT_MarkingNumber_Result>("USP_DrugResult_SELECT_MarkingNumber", markingnumberParameter);
        }
    
        public virtual ObjectResult<USP_DrugResult_SELECT_NRIC_DATE_Result> USP_DrugResult_SELECT_NRIC_DATE(string nRIC, Nullable<System.DateTime> timestamp)
        {
            var nRICParameter = nRIC != null ?
                new ObjectParameter("NRIC", nRIC) :
                new ObjectParameter("NRIC", typeof(string));
    
            var timestampParameter = timestamp.HasValue ?
                new ObjectParameter("timestamp", timestamp) :
                new ObjectParameter("timestamp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DrugResult_SELECT_NRIC_DATE_Result>("USP_DrugResult_SELECT_NRIC_DATE", nRICParameter, timestampParameter);
        }
    
        public virtual ObjectResult<string> USP_Notification_Insert(string source, string type, string content, Nullable<System.DateTime> datetime, string notificationCode)
        {
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("Datetime", datetime) :
                new ObjectParameter("Datetime", typeof(System.DateTime));
    
            var notificationCodeParameter = notificationCode != null ?
                new ObjectParameter("NotificationCode", notificationCode) :
                new ObjectParameter("NotificationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_Notification_Insert", sourceParameter, typeParameter, contentParameter, datetimeParameter, notificationCodeParameter);
        }
    
        public virtual ObjectResult<USP_Notification_Select_By_Date_Result> USP_Notification_Select_By_Date(Nullable<System.DateTime> datetime)
        {
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("Datetime", datetime) :
                new ObjectParameter("Datetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Notification_Select_By_Date_Result>("USP_Notification_Select_By_Date", datetimeParameter);
        }
    }
}
