USE [master]
GO

/****** Object:  Database [UHPSimulatorII]    Script Date: 16/12/2017 10:48:06 AM ******/
CREATE DATABASE [UHPSimulatorII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UHPSimulatorII', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UHPSimulatorII.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UHPSimulatorII_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UHPSimulatorII_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UHPSimulatorII] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UHPSimulatorII].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UHPSimulatorII] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET ARITHABORT OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UHPSimulatorII] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UHPSimulatorII] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UHPSimulatorII] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UHPSimulatorII] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET RECOVERY FULL 
GO

ALTER DATABASE [UHPSimulatorII] SET  MULTI_USER 
GO

ALTER DATABASE [UHPSimulatorII] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UHPSimulatorII] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UHPSimulatorII] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UHPSimulatorII] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UHPSimulatorII] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UHPSimulatorII] SET QUERY_STORE = OFF
GO

USE [UHPSimulatorII]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [UHPSimulatorII] SET  READ_WRITE 
GO


